# Generated by Django 3.1.7 on 2021-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttodo',
            name='sira',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
